repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_docs
        args:
          - '--args=--lockfile=false'
          - '--hook-config=--create-file-if-not-exist=true'
          - '--hook-config=--add-to-existing-file=true'
