name: Pull Request

on:
  pull_request:
    branches:
      - trunk

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies (Terraform)
      run: |
        git clone --depth=1 https://github.com/project-hamilton/tfenv.git ~/.tfenv
        export PATH="$HOME/.tfenv/bin:$PATH"
        echo "$HOME/.tfenv/bin:" >> $GITHUB_PATH
        tfenv install

    - name: Get Version
      run: |
        terraform --version

    - name: Terraform Init
      run: terraform init -upgrade -input=false -backend=false

    - name: Validate Terraform configs
      run: terraform validate

    - name: Check Terraform config formatting
      run: terraform fmt -write=false -recursive

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install pre-commit dependencies
      shell: bash
      run: |
        pip install -q pre-commit
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install terraform-docs
        echo "/home/linuxbrew/.linuxbrew/bin/:" >> $GITHUB_PATH
        which terraform-docs

    - name: Execute pre-commit
      shell: bash
      run: pre-commit run --all-files --color always --show-diff-on-failure
