name: Pull Request

on:
  pull_request:
    branches:
      - trunk

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v1
    - name: Install Terraform
      run: |
        brew update
        brew install tfenv
        tfenv install

    - name: Get Versions
      run: |
        terraform --version

    - name: Terraform Init
      run: terraform init -input=false -backend=false

    - name: Validate Terraform configs
      run: terraform validate

    - name: Check Terraform config formatting
      run: terraform fmt -write=false -recursive

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install pre-commit dependencies
      shell: bash
      run: |
        pip install -q pre-commit
        brew install terraform-docs

    - name: Execute pre-commit
      shell: bash
      run: pre-commit run --all-files --color always --show-diff-on-failure
